=== fofancy/localStudyApi/apiConfiguration/src/main/resources/providers/providers-config-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://fofancy.com/schema/providers-config"
           xmlns="http://fofancy.com/schema/providers-config"
           elementFormDefault="qualified">


        <xs:complexType name="info-type">
            <xs:sequence>
                <xs:element name="wsdl-url" type="xs:string"/>
                <xs:element name="namespace" type="xs:string"/>
                <xs:element name="port-name" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="service-implementation-info-type">
            <xs:sequence>
                <xs:element name="service-name" type="xs:string"/>
                <xs:element name="info" type="info-type"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="services-implementations-type">
            <xs:sequence>
                <xs:element name="service-implementation-info" type="service-implementation-info-type" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="provider-type">
            <xs:sequence>
                <xs:element name="provider-name" type="xs:string"/>
                <xs:element name="services-implementations" type="services-implementations-type"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="providers-type">
            <xs:sequence>
                <xs:element name="provider" type="provider-type" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <xs:element name="providers" type="providers-type"/>
</xs:schema>

=== fofancy/localStudyApi/apiConfiguration/src/test/resources/providers/not-valid-providers-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<providers xmlns="http://fofancy.com/schema/providers-config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://fofancy.com/schema/providers-config providers-config-schema.xsd">
    <provider>
        <provider-name>Wiki</provider-name>
        <services>
            <service>
                <service-name>GeographicalObjectsInfoReceiver</service-name>
                <info>
                    <wsdl-url>http://localhost:10100/geographical-objects-info-receiver?wsdl</wsdl-url>
                    <namespace>http://fofancy.com/</namespace>
                    <port-name>GeographicalObjectsInfoReceiverPort</port-name>
                </info>
            </service>
            <service>
                <service-name>MapInfoReceiver</service-name>
                <info>
                    <wsdl-url>http://localhost:10100/map-info-receiver?wsdl</wsdl-url>
                    <namespace>http://fofancy.com/</namespace>
                </info>
            </service>
        </services>
    </provider>
</providers>

=== fofancy/localStudyApi/apiConfiguration/src/main/resources/providers/providers-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<providers xmlns="http://fofancy.com/schema/providers-config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://fofancy.com/schema/providers-config providers-config-schema.xsd">
    <provider>
        <provider-name>Wiki</provider-name>

        <services-implementations>
            <service-implementation-info>
                <service-name>GeographicalObjectsInfoReceiver</service-name>
                <info>
                    <wsdl-url>http://localhost:10100/geographical-objects-info-receiver?wsdl</wsdl-url>
                    <namespace>http://fofancy.com/</namespace>
                    <port-name>GeographicalObjectsInfoReceiverPort</port-name>
                </info>
            </service-implementation-info>
            <service-implementation-info>
                <service-name>MapInfoReceiver</service-name>
                <info>
                    <wsdl-url>http://localhost:10100/map-info-receiver?wsdl</wsdl-url>
                    <namespace>http://fofancy.com/</namespace>
                    <port-name>MapInfoReceiverPort</port-name>
                </info>
            </service-implementation-info>
        </services-implementations>
    </provider>
</providers>
